spring:
  application:
    name:libary-app

  redis:
    host: localhost
    port: 6379
    timeout: 100000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000
